core/blog/api/v1/urls.py
# from django.urls import path, include
from . import views

from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register("post", views.PostModelViewSet, basename="post")
router.register("category", views.CategoryModelViewSet, basename="category")
urlpatterns = router.urls

core/blog/urls.py
from django.urls import include, path
from . import views

app_name = "blog"

urlpatterns = [
    path("cbv-index/", views.IndexView.as_view(), name="cbv-index"),
    path(
        "go-to-maktabkhooneh/<int:pk>",
        views.RedirectToMaktabkhooneh.as_view(),
        name="go-to-maktabkhooneh",
    ),
    path("post/api/", views.PostListAPIView.as_view(), name="post-list-api"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/create/", views.PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/edit", views.PostEditView.as_view(), name="post-edit"),
    path(
        "post/<int:pk>/delete",
        views.PostDeleteView.as_view(),
        name="post-delete",
    ),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from rest_framework.documentation import include_docs_urls

# from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.http import HttpResponse


schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="This is a test api for maktabkhooneh project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="abolfazlms1400@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


def indexView(request):
    return HttpResponse("<h1>Index Page</h1>")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", indexView, name="index-view"),
    path("blog/", include("blog.urls")),
    path("blog/comments/", include("comments.urls")),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-docs/", include_docs_urls(title="API sample")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models

# from accounts.models import User
# from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse

# from accounts.models import Profile

User = get_user_model()


# Create your models here.
class Post(models.Model):
    """
    This is a class to define posts for blog app
    """

    # author = models.ForeignKey(Profile,on_delete=models.CASCADE)
    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    # author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    image = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.content[0:5]

    def get_absolute_api_url(self):
        return reverse("blog:api-v1:post-detail", kwargs={"pk": self.pk})


class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import Post


class PostForms(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "status", "category", "published_date"]

core/blog/api/v1/views.py
from rest_framework.decorators import action

from rest_framework.permissions import (
    IsAuthenticated,
    IsAuthenticatedOrReadOnly,
)
from rest_framework.response import Response
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from .paginations import DefaultPagination
from .serializer import PostSerializer, CategorySerializer
from blog.models import Post, Category


class PostModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = {
        "category": ["exact", "in"],
        "author": ["exact"],
        "status": ["exact"],
    }
    search_fields = ["title", "content"]
    ordering_fields = ["published_date"]
    pagination_class = DefaultPagination

    @action(methods=["get"], detail=False)
    def get_ok(self, request):
        return Response({"detail": "ok"})


class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

core/blog/views.py
# from django.shortcuts import get_object_or_404, render
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

# from django.views.generic.edit import FormView
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from .models import Post
from .forms import PostForms

# Create your views here.
# Function Base View show a template
'''
def indexView(request):
    """
    a function based view to show index page
    """
    name = "ali"
    context={"name":name}
    return render(request,"index.html",context)
'''


class IndexView(TemplateView):
    """
    a class based view to show index page
    """

    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["name"] = "ali"
        context["post"] = Post.objects.all()
        return context


""" FBV To Redirect
from django.shortcuts import redirect
def RedirectToMaktabkhooneh(request):
    return redirect('https://www.maktabkhooneh.com')
"""


class RedirectToMaktabkhooneh(RedirectView):
    url = "https://maktabkhooneh.com"

    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs["pk"])
        print(post)
        return super().get_redirect_url(*args, **kwargs)


class PostListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):

    permission_required = "blog.view_post"
    # model = Post
    queryset = Post.objects.all()
    context_object_name = "posts"
    paginate_by = 2
    ordering = "-id"
    # def get_queryset(self):
    #     posts = Post.objects.filter(status=True)
    #     # return super().get_queryset()
    #     return posts


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post


"""
class PostCreateView(FormView):
    template_name = 'blog/contact.html'
    form_class = PostForms
    success_url = '/blog/post/'

    def form_valid(self,form):
        form.save()
        return super().form_valid(form)
"""


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    # fields = ['author','title','content','status','category','published_date']
    form_class = PostForms
    success_url = "/blog/post/"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForms
    success_url = "/blog/post/"


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = "/blog/post/"


class PostListAPIView(TemplateView):
    template_name = "blog/post_list_api.html"

core/templates/blog/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form method="post">{%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="send message">
    </form>
</body>

</html>

core/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Post</title>
</head>
<body>
    <form method="post">{% csrf_token %} 
        <p>Are you sure you want to delete "{{ object }}"?</p>   
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>{{object.title}}</h1>
    <hr>
    <small>{{object.author}} - {{object.published_date}}</small>
    <p>{{object.content}}</p>
</body>

</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
</head>
<body>
    <form method="post">{%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="send message">
    </form>
</body>
</html>

core/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>blog posts</h1>
    <ol>
        {% for post in posts%}
        <li>        
            <a href="{% url 'blog:post-detail' pk=post.id %}">
                <h2>{{post.id}} - {{post.title}}</h2>
            </a>
            <a href="{% url 'blog:post-edit' pk=post.id %}">
                <h5>Edit</h5>
            </a>  
            <a href="{% url 'blog:post-delete' pk=post.id %}">
                <h5>Delete</h5>
            </a>           
            <small>{{post.author.first_name}} {{post.author.last_name}} {{post.published_date}}</small>            
        </li>
        {%endfor%}
    </ol>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>

</html>

core/templates/blog/post_list_api.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>blog posts</h1>
    <ol id="post-wrapper">
        <!-- <li>        
            <a href="">
                <h2>{{post.id}} - {{post.title}}</h2>
            </a>
            <a href="">
                <h5>Edit</h5>
            </a>  
            <a href="">
                <h5>Delete</h5>
            </a>           
            <small>{{post.author.first_name}} {{post.author.last_name}} {{post.published_date}}</small>            
        </li> -->
    </ol>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $.get("http://127.0.0.1:8000/blog/api/v1/post/",function(data, textStatus, jqXHR){
            wrapper = $('#post-wrapper');
            for (post of data.results){
                wrapper.append(`<li><a href="${post.absolute_url}"><h2>${post.title}</h2></a></li>`)
            }
           
            // alert('status : ' + textStatus + ',data : '+data);
            // console.log(data);
        });
    </script>
</body>

</html>